// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/google/wire"
	"github.com/jiangliangquan1/iot-streaming/basisdata/devices"
	"github.com/jiangliangquan1/iot-streaming/logger"
	"github.com/jiangliangquan1/iot-streaming/viperex"
	"github.com/jiangliangquan1/iot-streaming/webapi"
	"github.com/jiangliangquan1/iot-streaming/zlwebhook"
)

// Injectors from wire.go:

func InitializeApp(configfile string) App {
	option := ProvideViperExOption(configfile)
	viperEx := viperex.NewViperEx(option)
	configOptions := ProvideLoggerConfigOption(viperEx)
	logrusLogger := logger.NewLogger(configOptions)
	webApiConfigurer := NewWebApiConfigurer(logrusLogger)
	webApiServerOption := ProvideWebApiServerOption(viperEx, webApiConfigurer)
	zlWebHookController := zlwebhook.NewZlWebHookController(logrusLogger)
	deviceController := devices.NewDeviceController(logrusLogger)
	v := ProvideApiControllers(zlWebHookController, deviceController)
	iWebApiServer := webapi.NewWebApiServer(webApiServerOption, logrusLogger, v)
	app := NewIotStreamingApp(iWebApiServer)
	return app
}

// wire.go:

var ProviderSet = wire.NewSet(
	ProvideViperExOption, viperex.NewViperEx, ProvideLoggerConfigOption, logger.NewLogger, NewWebApiConfigurer,
	ProvideWebApiServerOption, zlwebhook.NewZlWebHookController, devices.NewDeviceController, webapi.NewWebApiServer, ProvideApiControllers,
	NewIotStreamingApp,
)
